[package]
name = "nu_plugin_extras"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = { version = "3.4.1", features = ["wayland-data-control"] }
fancy-regex = "0.14.0"
nu-plugin = "0.104.0"
nu-protocol = "0.104.0"
